---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/v1/products":
    post:
      summary: Creates a Product
      tags:
      - Products
      description: Create a new product
      parameters: []
      responses:
        '200':
          description: product created
          content: {}
        '422':
          description: invalid request
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                manufactory:
                  type: string
                cost_price:
                  type: number
              required:
              - name
              - manufactory
              - cost_price
  "/v1/products/{id}":
    put:
      summary: Update a product
      tags:
      - Products
      description: Update a product
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: number
      responses:
        '200':
          description: product updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  manufactory:
                    type: string
                  cost_price:
                    type: number
                required:
                - id
                - name
                - manufactory
                - cost_price
        '404':
          description: Product not found
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                manufactory:
                  type: string
                cost_price:
                  type: number
              required:
              - name
              - manufactory
              - cost_price
    get:
      summary: Retrieve a product
      tags:
      - Products
      description: Retrieve a product
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: number
      responses:
        '200':
          description: product found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  manufactory:
                    type: string
                  cost_price:
                    type: number
                required:
                - id
                - name
                - manufactory
                - cost_price
        '404':
          description: Product not found
          content: {}
    delete:
      summary: Delete a product
      tags:
      - Products
      description: Delete a product
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: number
      responses:
        '204':
          description: product deleted
          content: {}
        '404':
          description: Product not found
          content: {}
  "/v1/stock_items":
    post:
      summary: Create a product at a store
      tags:
      - StockItem
      description: Add item at a store stock
      parameters: []
      responses:
        '200':
          description: Item add to store stock
          content: {}
        '422':
          description: invalid request
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                product_id:
                  type: number
                store_id:
                  type: number
                quantity:
                  type: number
              required:
              - product_id
              - store_id
              - quantity
    patch:
      summary: Increase stock_item
      tags:
      - StockItem
      description: Increases a existing item on stock
      parameters: []
      responses:
        '200':
          description: Increase stocke item
          content: {}
        '404':
          description: invalid request
          content: {}
        '422':
          description: invalid request
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                product_id:
                  type: number
                store_id:
                  type: number
                quantity:
                  type: number
              required:
              - product_id
              - store_id
              - quantity
    delete:
      summary: Decrease stock_item
      tags:
      - StockItem
      description: Decrease a existing item on stock
      parameters: []
      responses:
        '200':
          description: decrease stock item
          content: {}
        '404':
          description: invalid request
          content: {}
        '422':
          description: invalid request
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                product_id:
                  type: number
                store_id:
                  type: number
                quantity:
                  type: number
              required:
              - product_id
              - store_id
              - quantity
  "/v1/stores":
    post:
      summary: Create a store
      tags:
      - Stores
      description: Create a new store
      parameters: []
      responses:
        '200':
          description: store created
          content: {}
        '422':
          description: invalid request
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                address:
                  type: string
              required:
              - name
              - address
  "/v1/stores/{id}":
    put:
      summary: Update a store
      tags:
      - Stores
      description: Update a store
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: number
      responses:
        '200':
          description: store updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  address:
                    type: string
                required:
                - id
                - name
                - address
        '404':
          description: Store not found
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                address:
                  type: string
              required:
              - name
              - address
    get:
      summary: Retrieve a stores
      tags:
      - Stores
      description: Retrieve a store
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: number
      responses:
        '200':
          description: Store found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  address:
                    type: string
                required:
                - id
                - name
                - address
        '404':
          description: Store not found
          content: {}
    delete:
      summary: Delete a store
      tags:
      - Stores
      description: Delete a store
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: number
      responses:
        '204':
          description: store deleted
          content: {}
        '404':
          description: Store not found
          content: {}
servers:
- url: https://roger-store-api.herokuapp.com
  variables:
    defaultHost:
      default: localhost:3000
